In [2]:
import numpy as np
fixData = np.load('aes_power_fixedkey.npz', allow_pickle=True)

In [4]:
lstFData = list(fixData)
print(lstFData)
fT = fixData['traces'] #二維矩陣20,000筆，len(fT[n])=15,000，<class 'numpy.float64'>
fP = fixData['plaintexts'] #二維矩陣20,000筆，len(fT[n])=16，<class 'numpy.uint8'>

['traces', 'plaintexts']


In [11]:
print(len(fT))
print(len(fT[0]))
print(fT)
print(type(fT[0][0]))

20000
15000
[[ 0.02000183  0.02000183  0.02000183 ...  0.02000183  0.02000183
   0.02000183]
 [ 0.02000183  0.02000183  0.02000183 ...  0.02000183  0.02000183
   0.02000183]
 [ 0.02000183 -0.0195843   0.02000183 ...  0.02000183  0.02000183
   0.02000183]
 ...
 [-0.00945428 -0.02000183 -0.01653888 ...  0.00600964  0.00266939
   0.00573251]
 [-0.00686546 -0.02000183 -0.00353681 ...  0.00547796  0.00366317
   0.00635637]
 [-0.01144244 -0.02000183 -0.02000183 ...  0.00730436  0.00483091
   0.00726956]]
<class 'numpy.float64'>


In [12]:
print(len(fP))
print(len(fP[0]))
print(fP)
print(type(fP[0][0]))

20000
16
[[ 93  19  22 ... 120 114 248]
 [196 118 171 ... 194 114 146]
 [153 118 107 ... 166   4 131]
 ...
 [126  99 182 ... 151 168 104]
 [145  40  73 ...  98  58  27]
 [ 94  72 215 ... 238   6 204]]
<class 'numpy.uint8'>
