In [1]:
import numpy as np

In [26]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(np.__version__)

[1 2 3 4 5]
1.18.5


In [27]:
#Create a NumPy ndarray Object
'''
NumPy is used to work with arrays. The array object in NumPy 
is called ndarray.
We can create a NumPy ndarray object by using the array() function.
'''
arr = np.array([1, 2, 3, 4, 5])
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
'''
To create an ndarray, we can pass a list, 
tuple or any array-like object into the array() method,
and it will be converted into an ndarray
'''
arr = np.array((1, 2, 3, 4, 5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
'''
0-D arrays, or Scalars, 
are the elements in an array. 
Each value in an array is a 0-D array.
'''
arr = np.array(42) #0-D array
print(arr)

42


In [8]:
'''
An array that has 0-D arrays as its elements 
is called uni-dimensional or 1-D array.
These are the most common and basic arrays.
'''
arr = np.array([1, 2, 3, 4, 5])  #1-D array
print(arr)

[1 2 3 4 5]


In [10]:
'''
An array that has 1-D arrays as its elements is called a 2-D array.
These are often used to represent matrix or 2nd order tensors.
'''
arr = np.array([[1, 2, 3], [4, 5, 6]]) #2-D array
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
'''
An array that has 2-D arrays (matrices) as its elements 
is called 3-D array.
These are often used to represent a 3rd order tensor
'''
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [12]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [13]:
#Higher Dimensional Arrays
'''
An array can have any number of dimensions.
When the array is created, you can define the number of 
dimensions by using the ndmin argument.
'''
arr = np.array([1, 2, 3, 4], ndmin = 5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [14]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [16]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])
print(arr[1,4])

2nd element on 1st dim:  2
10


In [17]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


6


In [18]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])


[2 4]


In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [23]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[1, :])

[7 8 9]
[ 6  7  8  9 10]


In [24]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [25]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [28]:
'''
The NumPy array object has a property called dtype that 
returns the data type of the array:
'''
arr = np.array([1, 2, 3, 4])

print(arr.dtype)


int32


In [31]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)   #<U6是string的意思

<U6


In [32]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype) #|S1是string的意思

[b'1' b'2' b'3' b'4']
|S1


In [33]:
arr = np.array([1, 2, 3, 4], dtype='i4')
#Create an array with data type 4 bytes integer:
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [34]:
#Converting Data Type on Existing Arrays
'''
The best way to change the data type of an existing array, 
is to make a copy of the array with the astype() method.
'''
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [35]:
#COPY
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [36]:
#VIEW
#The view SHOULD be affected by the changes made to the original array.

arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [37]:
#VIEW
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [38]:
#Check if Array Owns it's Data
'''
As mentioned above, copies owns the data, and views does not own the data,
but how can we check this?

Every NumPy array has the attribute base that returns None 
if the array owns the data.

Otherwise, the base  attribute refers to the original object.
'''


arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)


'''
The copy returns None.
The view returns the original array.
'''

None
[1 2 3 4 5]


In [39]:
#Shape of an Array
'''
The shape of an array is the number of elements in each dimension.
'''
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)


(2, 4)


In [40]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


#### Reshaping arrays

In [41]:
#Reshape From 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [42]:
#Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [44]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)
#The example above returns the original array, so it is a view!!!!!!!!!!



[1 2 3 4 5 6 7 8]


In [49]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [50]:
#Flattening the arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)


[1 2 3 4 5 6]


# Iterating Arrays
### Iterating means going through elements one by one.

### As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

### If we iterate on a 1-D array it will go through each element one by one.

In [51]:
arr = np.array([1, 2, 3])
for i in arr:
    print(i)

1
2
3


In [52]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [54]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)


1
2
3
4
5
6


In [55]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [58]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [59]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)


(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [60]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [61]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)
